# Site
title: "Lawrence Wang"
description: ""
favicon: "assets/images/favicon.ico"
url: "http://www.rencewang.com"
baseurl: "http://www.rencewang.com"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

assets:
  sources:
    - assets
    - assets/images
    - assets/scripts
    - assets/styles
    - assets/fonts