# Site
name: "Lawrence Wang"
title: "Lawrence Wang"
description: "Personal site for Lawrence Wang, currently a student at Yale University, intereted in art, economics, and computer science, aspiring to become a designer and developer for the world wide web."
favicon: "/assets/images/favicon.ico"
url: "https://www.rencewang.com"
baseurl: "https://www.rencewang.com"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
