# Site
title: "Lawrence Wang"
description: ""
favicon: "/assets/images/favicon.ico"
url: "https://www.rencewang.com"
baseurl: "https://www.rencewang.com"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
