# Site
title: "Lawrence Wang"
name: "Lawrence Wang"
description: ""
favicon: "assets/images/favicon.ico"
url: "http://www.rencewang.com/newsite"
baseurl: "http://www.rencewang.com/newsite"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
